dotenv: .env

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contract@1.1.1'

networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'    # search gg: chainlink eth price feed, lấy address ở rinkeby
    verify: true
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'    # lấy address ở mainnet
    verify: False
  development:
    verify: False
  ganache-local: 
    verify: False
    
wallets:
  from_key: ${PRIVATE_KEY}